// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2vJZ0Ue1NuQHvqKbvefA4O8XWcf48V4',
    appId: '1:361779326656:web:02242135a39f1aa30c4725',
    messagingSenderId: '361779326656',
    projectId: 'treasuregame-2e6d9',
    authDomain: 'treasuregame-2e6d9.firebaseapp.com',
    storageBucket: 'treasuregame-2e6d9.firebasestorage.app',
    measurementId: 'G-S4QSJK8GMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4AZfBfu5Igy0OJfj0Ck7EpJtSBtD2dMY',
    appId: '1:361779326656:android:ca1eab00b3f2f97d0c4725',
    messagingSenderId: '361779326656',
    projectId: 'treasuregame-2e6d9',
    storageBucket: 'treasuregame-2e6d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO3qHO8a20roM7uHzVmvN-M06zncIvkqU',
    appId: '1:361779326656:ios:42d383bea888392e0c4725',
    messagingSenderId: '361779326656',
    projectId: 'treasuregame-2e6d9',
    storageBucket: 'treasuregame-2e6d9.firebasestorage.app',
    iosBundleId: 'com.example.treasureGameAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO3qHO8a20roM7uHzVmvN-M06zncIvkqU',
    appId: '1:361779326656:ios:42d383bea888392e0c4725',
    messagingSenderId: '361779326656',
    projectId: 'treasuregame-2e6d9',
    storageBucket: 'treasuregame-2e6d9.firebasestorage.app',
    iosBundleId: 'com.example.treasureGameAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx2vJZ0Ue1NuQHvqKbvefA4O8XWcf48V4',
    appId: '1:361779326656:web:b03c0ed319e6a1090c4725',
    messagingSenderId: '361779326656',
    projectId: 'treasuregame-2e6d9',
    authDomain: 'treasuregame-2e6d9.firebaseapp.com',
    storageBucket: 'treasuregame-2e6d9.firebasestorage.app',
    measurementId: 'G-ZSYDZW6W3Y',
  );

}