// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_FoNEBs-G1-tYWdwBMLGa5nK8E8_39mA',
    appId: '1:273446768987:web:3e0444d8278cae9e7f0a7e',
    messagingSenderId: '273446768987',
    projectId: 'treasuregame-4d8bb',
    authDomain: 'treasuregame-4d8bb.firebaseapp.com',
    storageBucket: 'treasuregame-4d8bb.firebasestorage.app',
    measurementId: 'G-157BMX5DCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0sFW4QrorlnG_QNQbki3dDs4jMMSdxZM',
    appId: '1:273446768987:android:c78b360ea2069f2d7f0a7e',
    messagingSenderId: '273446768987',
    projectId: 'treasuregame-4d8bb',
    storageBucket: 'treasuregame-4d8bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOdq38pIaKfQ1FmEp_PX4zs4fJ4f_lq5k',
    appId: '1:273446768987:ios:e1b2eeddfee8671d7f0a7e',
    messagingSenderId: '273446768987',
    projectId: 'treasuregame-4d8bb',
    storageBucket: 'treasuregame-4d8bb.firebasestorage.app',
    iosBundleId: 'com.example.treasureGameAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOdq38pIaKfQ1FmEp_PX4zs4fJ4f_lq5k',
    appId: '1:273446768987:ios:e1b2eeddfee8671d7f0a7e',
    messagingSenderId: '273446768987',
    projectId: 'treasuregame-4d8bb',
    storageBucket: 'treasuregame-4d8bb.firebasestorage.app',
    iosBundleId: 'com.example.treasureGameAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnlFI6FiHJVV6mhoYwouG-n6FTxSNTHoA',
    appId: '1:273446768987:web:8fe720cfcd802d327f0a7e',
    messagingSenderId: '273446768987',
    projectId: 'treasuregame-4d8bb',
    authDomain: 'treasuregame-4d8bb.firebaseapp.com',
    storageBucket: 'treasuregame-4d8bb.firebasestorage.app',
    measurementId: 'G-XFEM72R08C',
  );
}
